### PR TITLE
Correcting bug

### PR DESCRIPTION
**Pull request by qwertygc**
i correcting bug with highlight.

### CODE REVIEW

**Comment by cesarparent** [comment]
I could have committed if you wanted to, but that seems fine. Although the bug is also present in rejectEdits() (the fix is the exact same).

**Comment by cesarparent** [comment]
I've just pushed an update which fixes the bug and updates the test suite to take highlights and comments into account

**Comment by qwertygc** [comment]
It's done. for the same occasion, a correct a bug in parser (for html). I hope that script work!

**Comment by cesarparent** [comment]
Perfect, passes the tests!

**Pull request merged**
